# version: "3.8"

# services:
#   nuxt-app:
#     build:
#       context: .
#     ports:
#       - "3000:3000"
#     environment:
#       - PORT=3000
#       - NODE_ENV=production
#     restart: always
